import "./globals.scss"
import type { Metadata } from "next";
import Menu from "@/components/Menu";
import { Plus_Jakarta_Sans, Inter } from 'next/font/google';
import Footer from "@/components/commons/Footer";
import SmoothScroll from "@/components/commons/SmoothScroll";

const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['200','300','400','500','600','700','800'],
  variable: '--font-jakarta',
});

const inter = Inter({
  subsets: ["latin"],
  weight: ['200','300','400','500','600','700','800'],
  variable: '--font-inter'

});


export const metadata: Metadata = {
  title: "Reynoso Bienes Raices | Oportunidades Inmobiliarias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${inter.variable} ${jakarta.variable}`}
      >
        <SmoothScroll>
          <Menu />
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
