import "./globals.scss"
import type { Metadata } from "next";
import Menu from "@/components/Menu";
import { Plus_Jakarta_Sans, Inter, Kadwa, Poppins } from 'next/font/google';
import SmoothScroll from "@/components/commons/SmoothScroll";

const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['200','300','400','500','600','700','800'],
  variable: '--font-jakarta',
});

const inter = Inter({
  subsets: ["latin"],
  weight: ['200','300','400','500','600','700','800'],
  variable: '--font-inter'

});

const kadwa = Kadwa({
  subsets: ['latin'],
  weight: ['400','700'],
  variable: '--font-kadwa',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400','500','600','700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Reynoso Bienes Raices | Oportunidades Inmobiliarias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${inter.variable} ${jakarta.variable} ${kadwa.variable} ${poppins.variable}`}
      >
        <SmoothScroll>
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
