import "./globals.scss"
import type { Metadata } from "next";
import MobileMenu from "@/components/MobileMenu";
import { Plus_Jakarta_Sans, Inter } from 'next/font/google';
import Footer from "@/components/commons/Footer";

const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['200','300','400','500','600','700','800'],
  variable: '--font-jakarta',
});

const inter = Inter({
  subsets: ["latin"],
  weight: ['200','300','400','500','600','700','800'],
  variable: '--font-inter'

});


export const metadata: Metadata = {
  title: "Reynoso Bienes Raices | Oportunidades Inmobiliarias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${inter.variable} ${jakarta.variable}`}
      >
        <MobileMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
